
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 27 13:39:07 ART 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 45;
  public static final int PARENTESIS_IZQ = 36;
  public static final int PUNTO_Y_COMA = 31;
  public static final int RESTA = 15;
  public static final int CONTINUE = 4;
  public static final int CORCHETE_DER = 35;
  public static final int PORCENTAJE = 21;
  public static final int INT = 39;
  public static final int FOR = 7;
  public static final int LLAVE_IZQ = 32;
  public static final int IGUALDAD_LOGICA = 24;
  public static final int CLASS = 3;
  public static final int INCREMENTO = 19;
  public static final int SUMA = 14;
  public static final int IF = 9;
  public static final int ID = 8;
  public static final int BOOLEAN = 41;
  public static final int EOF = 0;
  public static final int PARENTESIS_DER = 37;
  public static final int RETURN = 10;
  public static final int TRUE = 11;
  public static final int DECREMENTO = 20;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int MENOR = 27;
  public static final int BREAK = 2;
  public static final int EXTERNINVK = 42;
  public static final int VOID = 12;
  public static final int ADMIRACION = 38;
  public static final int ASIGNACION = 18;
  public static final int MAYOR = 26;
  public static final int DIFERENCIA_LOGICA = 25;
  public static final int ELSE = 5;
  public static final int LLAVE_DER = 33;
  public static final int WHILE = 13;
  public static final int CORCHETE_IZQ = 34;
  public static final int MAYOR_IGUAL = 28;
  public static final int FLOAT = 40;
  public static final int CONJUNCION = 22;
  public static final int DISYUNCION = 23;
  public static final int MENOR_IGUAL = 29;
  public static final int FLOAT_LITERAL = 44;
  public static final int FALSE = 6;
  public static final int DIVISION = 17;
  public static final int INT_LITERAL = 43;
  public static final int MULTIPLICACION = 16;
}

