/* The following code was generated by JFlex 1.6.0 */

/*
Proyecto: Proyecto Compiladores 2014
Autores: Federico Franco, Bruno Isoardi
Funcionalidad: Clase que implementa un analizador lexico
*/
/*AQUI PUEDEN IR LOS IMPORTS */

import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>Lexer.lex</tt>
 */
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENTARIOSIMPLE = 2;
  public static final int COMENTARIOMULTIPLE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\54\1\55\1\57\1\56\1\56\22\0\1\54\1\16\1\4"+
    "\2\0\1\15\1\52\1\0\1\45\1\46\1\7\1\13\1\41\1\14"+
    "\1\5\1\6\12\1\1\0\1\42\1\11\1\12\1\10\2\0\32\2"+
    "\1\47\1\0\1\50\1\0\1\3\1\0\1\23\1\17\1\27\1\36"+
    "\1\22\1\34\1\2\1\40\1\32\1\2\1\26\1\21\1\2\1\24"+
    "\1\20\2\2\1\25\1\30\1\31\1\33\1\35\1\37\1\51\2\2"+
    "\1\43\1\53\1\44\7\0\1\57\u1fa2\0\1\57\1\57\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\11\3\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\2\1"+
    "\1\25\1\26\1\25\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\11\3\1\40\5\3"+
    "\1\41\1\42\1\43\10\3\1\44\1\45\6\3\1\46"+
    "\4\3\1\47\2\3\1\50\2\3\1\51\3\3\1\52"+
    "\1\53\1\54\1\55\2\3\1\56\1\3\1\57\3\3"+
    "\1\60\1\3\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\220\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\220\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\u0420\0\220\0\220\0\220\0\220\0\220\0\220\0\220"+
    "\0\220\0\u0450\0\u0480\0\220\0\220\0\u04b0\0\u04e0\0\u0120"+
    "\0\220\0\220\0\220\0\220\0\220\0\220\0\220\0\220"+
    "\0\220\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630"+
    "\0\u0660\0\u0690\0\360\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780"+
    "\0\220\0\220\0\u04e0\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870"+
    "\0\u08a0\0\u08d0\0\u0900\0\360\0\360\0\u0930\0\u0960\0\u0990"+
    "\0\u09c0\0\u09f0\0\u0a20\0\360\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0"+
    "\0\360\0\u0b10\0\u0b40\0\360\0\u0b70\0\u0ba0\0\360\0\u0bd0"+
    "\0\u0c00\0\u0c30\0\360\0\360\0\360\0\360\0\u0c60\0\u0c90"+
    "\0\360\0\u0cc0\0\360\0\u0cf0\0\u0d20\0\u0d50\0\360\0\u0d80"+
    "\0\360";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\4\1\7\1\4\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\2\6\1\22\2\6\1\23\1\6\1\24\1\6\1\25"+
    "\1\26\1\6\1\27\1\30\1\6\1\31\1\6\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\6"+
    "\1\42\1\43\3\44\1\0\55\44\1\45\2\0\7\44"+
    "\1\46\47\44\62\0\1\5\3\0\1\47\53\0\3\6"+
    "\13\0\22\6\10\0\1\6\6\0\4\50\1\51\53\50"+
    "\6\0\1\52\1\53\62\0\1\54\57\0\1\55\57\0"+
    "\1\56\57\0\1\57\57\0\1\60\57\0\1\61\46\0"+
    "\3\6\13\0\1\6\1\62\4\6\1\63\13\6\10\0"+
    "\1\6\7\0\3\6\13\0\2\6\1\64\17\6\10\0"+
    "\1\65\7\0\3\6\13\0\3\6\1\66\16\6\10\0"+
    "\1\6\7\0\3\6\13\0\1\6\1\67\1\70\17\6"+
    "\10\0\1\6\7\0\3\6\13\0\6\6\1\71\13\6"+
    "\10\0\1\6\7\0\3\6\13\0\5\6\1\72\7\6"+
    "\1\73\4\6\10\0\1\6\7\0\3\6\13\0\1\6"+
    "\1\74\1\75\1\6\1\76\15\6\10\0\1\6\7\0"+
    "\3\6\13\0\1\6\1\77\20\6\10\0\1\6\7\0"+
    "\3\6\13\0\21\6\1\100\10\0\1\6\60\0\1\101"+
    "\60\0\1\102\12\0\1\45\52\0\1\103\57\0\3\6"+
    "\13\0\1\6\1\104\20\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\105\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\11\6\1\106\10\6\10\0\1\6\7\0\3\6"+
    "\13\0\12\6\1\107\7\6\10\0\1\6\7\0\3\6"+
    "\13\0\12\6\1\110\7\6\10\0\1\6\7\0\3\6"+
    "\13\0\5\6\1\111\14\6\10\0\1\6\7\0\3\6"+
    "\13\0\4\6\1\112\15\6\10\0\1\6\7\0\3\6"+
    "\13\0\14\6\1\113\5\6\10\0\1\6\7\0\3\6"+
    "\13\0\12\6\1\114\7\6\10\0\1\6\7\0\3\6"+
    "\13\0\6\6\1\115\13\6\10\0\1\6\7\0\3\6"+
    "\13\0\1\6\1\116\20\6\10\0\1\6\7\0\3\6"+
    "\13\0\2\6\1\117\17\6\10\0\1\6\7\0\3\6"+
    "\13\0\13\6\1\120\6\6\10\0\1\6\7\0\3\6"+
    "\13\0\13\6\1\121\6\6\10\0\1\6\7\0\3\6"+
    "\13\0\2\6\1\122\17\6\10\0\1\6\7\0\3\6"+
    "\13\0\4\6\1\123\15\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\124\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\125\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\14\6\1\126\5\6\10\0\1\6\7\0\3\6"+
    "\13\0\12\6\1\127\7\6\10\0\1\6\7\0\3\6"+
    "\13\0\11\6\1\130\10\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\131\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\4\6\1\132\15\6\10\0\1\6\7\0\3\6"+
    "\13\0\11\6\1\133\10\6\10\0\1\6\7\0\3\6"+
    "\13\0\17\6\1\134\2\6\10\0\1\6\7\0\3\6"+
    "\13\0\2\6\1\135\17\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\136\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\7\6\1\137\12\6\10\0\1\6\7\0\3\6"+
    "\13\0\6\6\1\140\13\6\10\0\1\6\7\0\3\6"+
    "\13\0\6\6\1\141\13\6\10\0\1\6\7\0\3\6"+
    "\13\0\13\6\1\142\6\6\10\0\1\6\7\0\3\6"+
    "\13\0\11\6\1\143\10\6\10\0\1\6\7\0\3\6"+
    "\13\0\12\6\1\144\7\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\145\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\146\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\4\6\1\147\15\6\10\0\1\6\7\0\3\6"+
    "\13\0\5\6\1\150\14\6\10\0\1\6\7\0\3\6"+
    "\13\0\5\6\1\151\14\6\10\0\1\6\7\0\3\6"+
    "\13\0\5\6\1\152\14\6\10\0\1\6\7\0\3\6"+
    "\13\0\5\6\1\153\14\6\10\0\1\6\7\0\3\6"+
    "\13\0\13\6\1\154\6\6\10\0\1\6\7\0\3\6"+
    "\13\0\14\6\1\155\5\6\10\0\1\6\7\0\3\6"+
    "\13\0\5\6\1\156\14\6\10\0\1\6\7\0\3\6"+
    "\13\0\3\6\1\157\16\6\10\0\1\6\7\0\3\6"+
    "\13\0\16\6\1\160\3\6\10\0\1\6\7\0\3\6"+
    "\13\0\7\6\1\161\12\6\10\0\1\6\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3504];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\4\1\1\11\5\1\1\11\12\1\10\11"+
    "\2\1\2\11\1\1\2\0\11\11\17\1\2\11\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("error: "+yychar +" "+ yyline +" "+ yytext());
          }
        case 50: break;
        case 2: 
          { return new Symbol(sym.INT_LITERAL, yychar, yyline, yytext());
          }
        case 51: break;
        case 3: 
          { return new Symbol(sym.ID, yychar, yyline, yytext());
          }
        case 52: break;
        case 4: 
          { return new Symbol(sym.DIVISION, yychar, yyline, yytext());
          }
        case 53: break;
        case 5: 
          { return new Symbol(sym.MULTIPLICACION, yychar, yyline, yytext());
          }
        case 54: break;
        case 6: 
          { return new Symbol(sym.MAYOR, yychar, yyline, yytext());
          }
        case 55: break;
        case 7: 
          { return new Symbol(sym.MENOR, yychar, yyline, yytext());
          }
        case 56: break;
        case 8: 
          { return new Symbol(sym.ASIGNACION, yychar, yyline, yytext());
          }
        case 57: break;
        case 9: 
          { return new Symbol(sym.SUMA, yychar, yyline, yytext());
          }
        case 58: break;
        case 10: 
          { return new Symbol(sym.RESTA, yychar, yyline, yytext());
          }
        case 59: break;
        case 11: 
          { return new Symbol(sym.PORCENTAJE, yychar, yyline, yytext());
          }
        case 60: break;
        case 12: 
          { return new Symbol(sym.ADMIRACION, yychar, yyline, yytext());
          }
        case 61: break;
        case 13: 
          { return new Symbol(sym.COMA, yychar, yyline, yytext());
          }
        case 62: break;
        case 14: 
          { return new Symbol(sym.PUNTO_Y_COMA, yychar, yyline, yytext());
          }
        case 63: break;
        case 15: 
          { return new Symbol(sym.LLAVE_IZQ, yychar, yyline, yytext());
          }
        case 64: break;
        case 16: 
          { return new Symbol(sym.LLAVE_DER, yychar, yyline, yytext());
          }
        case 65: break;
        case 17: 
          { return new Symbol(sym.PARENTESIS_IZQ, yychar, yyline, yytext());
          }
        case 66: break;
        case 18: 
          { return new Symbol(sym.PARENTESIS_DER, yychar, yyline, yytext());
          }
        case 67: break;
        case 19: 
          { return new Symbol(sym.CORCHETE_IZQ, yychar, yyline, yytext());
          }
        case 68: break;
        case 20: 
          { return new Symbol(sym.CORCHETE_DER, yychar, yyline, yytext());
          }
        case 69: break;
        case 21: 
          { 
          }
        case 70: break;
        case 22: 
          { yybegin(YYINITIAL);
          }
        case 71: break;
        case 23: 
          { return new Symbol(sym.STRING_LITERAL, yychar, yyline, yytext());
          }
        case 72: break;
        case 24: 
          { yybegin(COMENTARIOSIMPLE);
          }
        case 73: break;
        case 25: 
          { yybegin(COMENTARIOMULTIPLE);
          }
        case 74: break;
        case 26: 
          { return new Symbol(sym.MAYOR_IGUAL, yychar, yyline, yytext());
          }
        case 75: break;
        case 27: 
          { return new Symbol(sym.MENOR_IGUAL, yychar, yyline, yytext());
          }
        case 76: break;
        case 28: 
          { return new Symbol(sym.IGUALDAD_LOGICA, yychar, yyline, yytext());
          }
        case 77: break;
        case 29: 
          { return new Symbol(sym.INCREMENTO, yychar, yyline, yytext());
          }
        case 78: break;
        case 30: 
          { return new Symbol(sym.DECREMENTO, yychar, yyline, yytext());
          }
        case 79: break;
        case 31: 
          { return new Symbol(sym.DIFERENCIA_LOGICA, yychar, yyline, yytext());
          }
        case 80: break;
        case 32: 
          { return new Symbol(sym.IF, yychar, yyline, yytext());
          }
        case 81: break;
        case 33: 
          { return new Symbol(sym.CONJUNCION, yychar, yyline, yytext());
          }
        case 82: break;
        case 34: 
          { return new Symbol(sym.DISYUNCION, yychar, yyline, yytext());
          }
        case 83: break;
        case 35: 
          { return new Symbol(sym.FLOAT_LITERAL, yychar, yyline, yytext());
          }
        case 84: break;
        case 36: 
          { return new Symbol(sym.INT, yychar, yyline, yytext());
          }
        case 85: break;
        case 37: 
          { return new Symbol(sym.FOR, yychar, yyline, yytext());
          }
        case 86: break;
        case 38: 
          { return new Symbol(sym.ELSE, yychar, yyline, yytext());
          }
        case 87: break;
        case 39: 
          { return new Symbol(sym.TRUE, yychar, yyline, yytext());
          }
        case 88: break;
        case 40: 
          { return new Symbol(sym.VOID, yychar, yyline, yytext());
          }
        case 89: break;
        case 41: 
          { return new Symbol(sym.BREAK, yychar, yyline, yytext());
          }
        case 90: break;
        case 42: 
          { return new Symbol(sym.CLASS, yychar, yyline, yytext());
          }
        case 91: break;
        case 43: 
          { return new Symbol(sym.FLOAT, yychar, yyline, yytext());
          }
        case 92: break;
        case 44: 
          { return new Symbol(sym.FALSE, yychar, yyline, yytext());
          }
        case 93: break;
        case 45: 
          { return new Symbol(sym.WHILE, yychar, yyline, yytext());
          }
        case 94: break;
        case 46: 
          { return new Symbol(sym.RETURN, yychar, yyline, yytext());
          }
        case 95: break;
        case 47: 
          { return new Symbol(sym.BOOLEAN, yychar, yyline, yytext());
          }
        case 96: break;
        case 48: 
          { return new Symbol(sym.CONTINUE, yychar, yyline, yytext());
          }
        case 97: break;
        case 49: 
          { return new Symbol(sym.EXTERNINVK, yychar, yyline, yytext());
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {  return new Symbol(sym.EOF, new String("Fin Del Archivo"));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
